//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ABMEntities : DbContext
    {
        public ABMEntities()
            : base("name=ABMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumnos> alumnos { get; set; }
        public virtual DbSet<aulas> aulas { get; set; }
        public virtual DbSet<clases> clases { get; set; }
        public virtual DbSet<cursos> cursos { get; set; }
        public virtual DbSet<instructores> instructores { get; set; }
        public virtual DbSet<materias> materias { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<view_cursos> view_cursos { get; set; }
        public virtual DbSet<testLoco> testLoco { get; set; }
        public virtual DbSet<VIEW_ALUMNOS> VIEW_ALUMNOS { get; set; }
    
        public virtual int INS_NUEVO_ALUMNO(string nombre, string apellido, ObjectParameter new_MEM_BASIC_ID)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_NUEVO_ALUMNO", nombreParameter, apellidoParameter, new_MEM_BASIC_ID);
        }
    }
}
