//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cursos
    {
        public int id_curso { get; set; }
        public int id_instructor { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int id_materia { get; set; }
        public string materia { get; set; }
        public string programa { get; set; }
        public int codigo_aula { get; set; }
        public int capacidad { get; set; }
    }
}
